apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
  name: login
spec:
  ports:
    - name: ssh
      port: {{ .Values.login.ports.ssh }}
      targetPort: 22
    - name: apache
      port: {{ .Values.login.ports.http }}
      targetPort: 80
      protocol: TCP
    - name: https
      port: {{ .Values.login.ports.https }}
      targetPort: 443
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
    
