---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.slurmConf }}
data:
  cgroup.conf: {{ .Files.Get "files/cgroup.conf" | quote}}
  slurm.conf: {{ .Files.Get "files/slurm.conf" | quote}}

